language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
    - downloads
env:
  global:
    - BINARYBUILDER_AUTOMATIC_APPLE=true
  matrix:
    - PART=1/3
    - PART=2/3
    - PART=3/3
sudo: required
jobs:
  include:
    - stage: regenerate build.jl
      script: julia build_tarballs.jl --only-buildjl
      if: tag IS present

# Before anything else, get the latest versions of things
before_script:
  - julia -e 'using Pkg;
      Pkg.add(PackageSpec(name="MbedTLS", version="0.6.6"));
      Pkg.pin(PackageSpec(name="MbedTLS", version="0.6.6"));
      Pkg.add([PackageSpec(name="BinaryBuilder", rev="master"), PackageSpec(name="BinaryProvider")])'

script:
  - julia build_tarballs.jl --part=$PART --verbose

deploy:
    provider: releases
    api_key:
        # Note; this api_key is only valid for quinnj/MbedTLSBuilder; you need
        # to make your own: https://docs.travis-ci.com/user/deployment/releases/
        secure: JAh+O0MJtokvQIIGPXncaeKfeAVl8ATr8hurCyjRyPYktxcEQ/hx6C/hb5KC8iC3WZBoTBYI0IDTy71EY32Zf+c7546RR59QceFNaFUcOur8ZwVKBnUAiLpxynGvAZg6uR9h3v5uw9omWUY1JvvucLAxqN873i1IH46M5KjqyXRiU7ARluNxqlwJ17rXWSEqXGDEgKeT4TmbM5BKiPabbm3Imu5gb5gCrXCMH4oK6nop8C2PO0DzPbhsLHeOJOjXURlffLrca8VeXylLLoCSjWrm5Y0YiPkjSaeklF4aiy1Y0bSLbpDSuwUVo4nZPsfm913II/1/qOVQzqjHUYMTpIeZ8mblqXQlfQ4opMJq4h6ttul430gXlRx5TQg2wjiZuvqnqRtrAVTzmX81cjoWVCbnLf45xZJrPdHWzvdD736oiekKDX8cYoBUiddDn1M10Ahrc2o/mdaFZIYzaN4C/iE0JJHsB0bWGN1+7nx0TS5pEhYoDigWl/TcdEEuUmQn7Wq0mwh7hC348bHaPfeFKso5jH2vNWB+SqZthWixbtJDSqqCtdjoVLYxWKkvhN6wpb9KBexs2KOSYT+zd1pJdalxakb6KiAC0/ZQvzhqC42NVnvOtMtmlnp97by+R1XyimK6eKmgvBrk6VyrTUInvXKGH+DxwcPC0DNas8OCJek=
    file_glob: true
    file: products/*
    skip_cleanup: true
    on:
        repo: JuliaWeb/MbedTLSBuilder
        tags: true
